import{i as l,S as g}from"./assets/vendor-9310f15c.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerpolicy&&(r.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?r.credentials="include":e.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const f="https://pixabay.com/api/";function d(o){const t=`?${new URLSearchParams({key:"42137546-386b5be41212ccd429cab5a80",q:o,image_type:"photo",orientation:"horizontal",safeSearch:!0})}`,n=f+t;return fetch(n).then(e=>e.json()).catch(e=>{throw console.error("Error fetching images:",e),e})}const p=document.getElementById("gallery"),h=document.querySelector(".search-form"),y=document.querySelector(".loader"),a={galleryContainer:p,searchForm:h,loaderContainer:y},m="gallery-link";function F({largeImageURL:o,tags:s,webformatURL:t,likes:n,views:e,comments:r,downloads:i}){return`
    <a href="${o}" class="${m}">
       <figure>
        <img src="${t}" alt="${s}" class="gallery-image">
        <figcaption class="gallery__figcaption">
          <div class="image-item">Likes <span class="image-elem">${n}</span></div>
          <div class="image-item">Views <span class="image-elem">${e}</span></div>
          <div class="image-item">Comments <span class="image-elem">${r}</span></div>
          <div class="image-item">Downloads <span class="image-elem">${i}</span></div>
    </figcaption>
    </figure>
  </a>
  `}const u={titleColor:"#FFFFFF",messageColor:"#FFFFFF",messageSize:"16px",position:"topRight",displayMode:"replace",closeOnEscape:!0,pauseOnHover:!1,maxWidth:432,messageSize:"16px",messageLineHeight:"24px"};function c(o){l.show({message:o,backgroundColor:"#EF4040",progressBarColor:"#FFE0AC",icon:"icon-close",...u})}function L(o){l.show({message:o,backgroundColor:"#59A10D",progressBarColor:"#B5EA7C",icon:"icon-chek",...u})}a.searchForm.addEventListener("submit",function(o){o.preventDefault();const s=o.target.elements.query.value;s!==""&&(a.galleryContainer.innerHTML="",a.loaderContainer.style.display="block",d(s).then(function({hits:t,total:n}){if(Array.isArray(t)&&t.length>0){const e=t.map(F).join("");a.galleryContainer.innerHTML=e,L(`Was found: ${n} images`),new g(`.${m}`).refresh()}else c("Sorry, there are no images matching your search query. Please try again!")}).catch(function(t){c(`Error fetching images: ${t}`)}).finally(function(){a.searchForm.reset(),a.loaderContainer.style.display="none"}))});
//# sourceMappingURL=commonHelpers.js.map
